### ISSUE TITLE
PHP questions awesome?

### ISSUE THREAD

**Issue by MrNicodemuz** [MaximAbramchuck/awesome-interview-questions#116]
Most articles talk about "echo" vs "print" and about how to do an "include". Seriously? Awesome? Most of the articles suggest interviewing like it's year 2005.

I would suggest adding something about composer, traits, namespaces, phpunit, frameworks (symfony, laravel), etc.

**Comment by rashidcricl** [comment]
same problem here
[https://scoutcoupon.com]()

**Comment by MaximAbramchuck** [comment]
Sorry, I'm not a PHP developer myself, so it's hard for me to validate these. If you don't mind sending a PR with improvements - I'd really appreciate it 👍
