### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by rasoolsomji** [MaximAbramchuck/awesome-interview-questions#144]
There are a couple of dead links in the Django section:

[Top 10 Django interview questions with their answers that you can encounter during the job interview for web developer](http://www.goodinterviewquestions.net/top-10-django-interview-questions-and-answers/)

[Django interview questions from f2finterview.com](http://www.f2finterview.com/web/Django/)

**Comment by julianorinyol** [comment]
i just discovered this one as well, and created a pull request to remove them.
https://github.com/MaximAbramchuck/awesome-interview-questions/pull/153

**Comment by ElviraBurchik** [comment]
Close the issue, thanks for pr!
