### ISSUE TITLE
Add More Custom Questions

### ISSUE THREAD

**Issue by ssimontis** [MaximAbramchuck/awesome-interview-questions#149]
Hey there,

First off, thank you for creating this list. I have noticed that a lot of the sites providing "megadumps" of interview questions tend to be on the lower end of the quality spectrum...poor spelling & grammar, misguided explanations, sometimes blatantly wrong information.

For at least a few of these categories, I think I can compile some more detailed questions. My career has been .NET focused, so it would probably be mostly C# and Javascript, perhaps a little F#. If I were to compile those lists, would you accept a PR?

**Comment by MaximAbramchuck** [comment]
Sure thing, go for it :)

**Comment by ElviraBurchik** [comment]
Close the issue
