### ISSUE TITLE
AngularJS, link 3 is broken - marked as private by author

### ISSUE THREAD

**Issue by fz-29** [MaximAbramchuck/awesome-interview-questions#71]
The link - AngularJS Interview Questions and Answers by Shailendra Chauhan (http://www.slideshare.net/proshailendra/angular-js-interview-questions-answers-by-shailendra-chauhan) is now made private by the author and is inaccessible.

**Comment by MaximAbramchuck** [comment]
solved by https://github.com/MaximAbramchuck/awesome-interview-questions/pull/72
