### ISSUE TITLE
URL is not working, please change from https to http

### ISSUE THREAD

**Issue by mescalito** [MaximAbramchuck/awesome-interview-questions#73]
Hi there!

This link is not working:

Algorithms:
Five programming problems every Software Engineer should be able to solve in less than 1 hour

This is wrong, watch for the https: 
https://www.shiftedup.com/2015/05/07/five-programming-problems-every-software-engineer-should-be-able-to-solve-in-less-than-1-hour

This is right, just http:
http://www.shiftedup.com/2015/05/07/five-programming-problems-every-software-engineer-should-be-able-to-solve-in-less-than-1-hour

URL is fine but just need to remove the "s" in http.

**Comment by MaximAbramchuck** [comment]
Cool, thanks, I'll fix it asap! By the way, where did you find my repo?

**Comment by mescalito** [comment]
reddit!

**Comment by MaximAbramchuck** [comment]
Fixed!
